### ISSUE TITLE
Safari rendering bug - box around annotation isn't removed

### ISSUE THREAD

**Issue by wykhuh** [annotorious/annotorious#398] opened 2024-05-01 21:36 UTC
I'm using Safari 16 on OSX 13 and Annotorious Openseadragon plugin. When users zoom and pan the image, lines from the box  around the annotation remain on screen. The lines for the previous position of the box aren't removed.  This bug does not happen in Chrome or Firefox.

<img width="654" alt="image" src="https://github.com/annotorious/annotorious/assets/6968611/205bfda9-53eb-4f50-94af-55d79edeeb77">

You can recreate this bug by viewing the Openseadragon plugin page using Safari.  https://annotorious.github.io/getting-started/osd-plugin/

**Comment by rsimon** [comment] 2024-05-23 05:21
I can reproduce the issue, and have seen it come and go on previous versions of Safari. Unfortunately, this appears to be a bug in Safari' SVG rendering engine. Which also means there's pretty much nothing I can do about it (unless someone can figure out what exactly triggers the bug, and whether there are workaround).

FWIW: the next major release of Annotorious OpenSeadragon will no longer use SVG but WebGL, which won't have this issue anymore.

**Comment by rsimon** [comment] 2024-09-06 16:11
Closing this as `won't fix` in v2.x. Meanwhile, Annotorious v3 is available, which does no longer have this bug. (Because OpenSeadragon rendering is based on WebGL, not SVG.)

**Closed as completed by rsimon** 2024-09-06 16:11 UTC
Labels: v2.x
