### ISSUE TITLE
Need to click and hold to select annotation

### ISSUE THREAD

**Issue by johnguirgis** [annotorious/annotorious#124] opened 2021-06-04 13:46 UTC
I am using Annotorious on a Drupal site to annotate images but I am running into an issue where I need to click and hold on an annotation in order to view it. This is only happening in `readOnly` mode. What's strange is that this is only occurring on images that are placed in the body of articles and not in images placed separately. Here is my initialization code:
```javascript
var anno = Annotorious.init({
    image: imgElement,
    readOnly: readOnly1 || window.location.search !== "?mode=annotation"
  });
  
  anno.setAuthInfo({'id': user_data.id, 'displayName': user_data.displayName});

  var page_url = window.location.pathname;

  jQuery.ajax({
    type: "GET",
    url: "/recogito_integration/get",
    dataType: 'json',
    headers: {
      'pageurl': page_url,
    },

    success: function (data) {
      console.log(data);
      for (annotation in data) {

        w3c = convert_annotation_w3c(data[annotation]);
        if(w3c.type != "Annotation" && imgElement["src"] == w3c["target"]["source"])
        {
          anno.addAnnotation(w3c);
        }
      }
    },
    error: function (xhr, status, error) {
      alert(xhr.responseText);
    }
  });

  anno.on('selectAnnotation', function (annotation) {
    highlightAnnotatedContent(annotation);

  });

  anno.on('createAnnotation', function (annotation) {
    create_annotation(annotation);
  });

  anno.on('updateAnnotation', function (annotation, previous) {

    console.log(annotation);
    console.log(previous);
    update_annotation(annotation, previous);
  });

  anno.on('deleteAnnotation', function (annotation) {
    delete_annotation(annotation);
  });

```
Thanks in advance for the help.

**Comment by rsimon** [comment] 2021-06-04 13:53
Hard to tell since that's definitely not the normal Annotorious behavior. When you click an annotation, that will fire the `selectAnnotation` event, so the question is: what does your `highlightAnnotatedContent` do?

**Comment by johnguirgis** [comment] 2021-06-04 14:04
`highlightAnnotatedContent` just hides some stuff for which the user does not have permission, but the issue is still there when I comment out that line.
Also just noticed that this occurs only for images within a `<p>` tag.

**Comment by rsimon** [comment] 2021-06-04 15:57
I just confirmed that this works as intended in Annotorious standard, v2.4, with image enclosed in `<p>`, in read-only mode. That means there must be something specific in your code.

If you can create a live example online where I can reproduce this, I'm happy to take a look.

**Comment by johnguirgis** [comment] 2021-06-04 16:48
Thanks.
I think I see the issue, for some reason the editor's `display` attribute is set to `none` so it is being hidden, I am working on fixing it now. Any idea why that might be?

**Comment by rsimon** [comment] 2021-06-23 18:46
Just checking: were you able to resolve this and/or figure out what's causing it?

**Comment by johnguirgis** [comment] 2021-06-23 20:33
I wasn't able to figure out what was causing the issue but I worked around it in CSS, 
```css

.r6o-editor{
  display: block !important;
}

```

**Comment by rsimon** [comment] 2021-06-24 06:25
Interesting. The editor is a `<div>` and has `block` as the default display property. I.e. this must be some external stylesheet on your page "bleeding through", and overriding the editor `<div>`s default display. In that case, forcing it back like you did is exactly the right way to fix it, I'd say. (I'm closing the issue.)

**Closed as completed by rsimon** 2021-06-24 06:25 UTC
