### ISSUE TITLE
Polygon points offset after drawing

### ISSUE THREAD

**Issue by shyampatil1** [annotorious/annotorious#48] opened 2020-08-06 15:26 UTC
Hello Team,

Polygon Points are not consistant

Sometimes its is showing <svg><polygon points="x,y x,y x,y"></polygon></svg>
sometimes <svg><polygon points="x,y,x,y,x,y"></polygon></svg>

**Comment by rsimon** [comment] 2020-08-06 15:34
Thanks for reporting. Can you let me know which browser (and OS) you are using? Can you identify any special conditions that seem to cause the problem? Or is it completely random?

**Comment by shyampatil1** [comment] 2020-08-07 12:04
Hi ,

I am using Latest Chrome version.

Points are generating randomly sometimes comma saperated like <svg><polygon points="1,2 2,3 4,5"></polygon>
sometimes it is giving <svg><polygon points="1,2,2,3,4,5"></polygon>

**Comment by shyampatil1** [comment] 2020-08-08 05:08
i am using latest version of Chrome

and Windows 10 64bit machine

**Comment by rsimon** [comment] 2020-08-16 11:17
Sorry, I cannot reproduce this. Do you have a screenshot of the issue? Or do you mean that when you edit a polygon shape and move the whole shape, only the shape moves but not the corner points? That was an unfinished piece of code which is now completed in the master branch.

**Comment by rsimon** [comment] 2020-09-06 06:25
Just bumping: are there any news on this?

**Comment by rsimon** [comment] 2020-09-13 07:09
I think I could finally reproduce this issue. Polygon corner handles are offset from the polygon, right after the polygon was created. Interestingly, this seems to happen _only_ in the compiled library, but never in development mode.

**Comment by rsimon** [comment] 2020-09-15 12:10
Turns out that this happend in both built and dev mode - but was actually related to scaled images. Polygon corner handles would be offset from their position when the image (and the SVG canvas) were resized from their natural width and height.

**Comment by adroit91** [comment] 2020-12-17 07:50
I'm seeing this in scaled images too. Any suggestions/fixes for the same?

**Comment by rsimon** [comment] 2020-12-20 17:19
I have recently revised the code that scales the shapes. Looks like this is now fixed in the [latest release](https://github.com/recogito/annotorious/releases/tag/v2.1.6) published just now.

**Closed as completed by rsimon** 2020-12-20 17:19 UTC
