### ISSUE TITLE
Error on demo page

### ISSUE THREAD

**Issue by ddankwerth** [annotorious/annotorious#66] opened 2020-11-01 09:04 UTC
Playing around on the demo page , i get 
Cannot read property removeChild
This happens after playing around and creating a really small squere![IMG_20201101_100209.jpg](https://user-images.githubusercontent.com/6493282/97797866-5332b100-1c29-11eb-828b-aec14c42124b.jpg)

**Comment by rsimon** [comment] 2020-11-01 09:07
The demo page isn't using the latest release. This should no longer be an issue in the current release.

**Comment by rsimon** [comment] 2020-11-01 09:10
Ouch sorry, it's in fact using one of the more recent ones (although not the latest). I'll look into it.

**Comment by rsimon** [comment] 2020-11-08 16:09
I was unable to reproduce this in the latest build. Closing for now, unless someone else manages to reproduce exact steps that might lead to this.

**Closed as completed by rsimon** 2020-11-08 16:09 UTC
