### ISSUE TITLE
Adding an annotation in existing annotation

### ISSUE THREAD

**Issue by yyhhkk12** [annotorious/annotorious#154] opened 2021-07-27 02:50 UTC
Hello. I'm trying drawing an annotation in existing annotation using polygon tool. But, it failed.
After dragging anywhere in annotation to start drawing,  if I click another point, existing annotation is selected..
Is there any way to draw polygon in existing annotation?

**Comment by rsimon** [comment] 2021-07-27 06:03
This works in the standard version. I'm assuming you are using the OpenSeadragon version? I.e. this is a duplicate of this: https://github.com/recogito/annotorious-openseadragon/issues/75

It's fixed already and will be available with the next release.

**Comment by yyhhkk12** [comment] 2021-07-27 06:34
> This works in the standard version. I'm assuming you are using the OpenSeadragon version? I.e. this is a duplicate of this: [recogito/annotorious-openseadragon#75](https://github.com/recogito/annotorious-openseadragon/issues/75)
> 
> It's fixed already and will be available with the next release.

Oh, sorry. I added `selectAnnotation`  event handler and handler calls `selectAnnotation` API depending on specific condition.
So, selection was canceled whenever `selectAnnotation` API called by clicking a point to draw polygon.

**Comment by rsimon** [comment] 2021-07-27 06:40
I'm not sure I understand your use case. You listening to the `selectAnnotation` event? And inside the handler you call `anno.selectAnnitation`? (To deselect the annotation again under certain conditions?)

Either way, the `selectAnnotation` event is not fired when you start creating a new annotation, except in the OpenSeadragon version because of the bug linked above. (Which is now fixed.)

**Closed as completed** 2021-07-27 06:41 UTC
