### ISSUE TITLE
Tags vocabulary does not work in 2.1.12

### ISSUE THREAD

**Issue by neocheema** [annotorious/annotorious#57] opened 2020-09-24 12:40 UTC
Hi, 

I just chanced upon this brilliant library, and would like to thank you for making my life easier. 

I can see a glitch while using predefined tags vocabulary with 2.1.12. I'm using 
   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@recogito/annotorious@2.1.2/dist/annotorious.min.css">
    <script src="https://cdn.jsdelivr.net/npm/@recogito/annotorious@2.1.2/dist/annotorious.min.js"></script>

I initialize like this

          var anno = Annotorious.init({
              image: 'targetimage',
              locale: 'auto',
              widgets: [ 
                 {widget: 'TAG', vocabulary: ['Animal', 'Building', 'Vegetation', 'Waterway']}
             ],
          });

So when I select an area, I can see the predefined vocabulary options. But when I click on one of the options, nothing get selected in the widget area. And clicking on "OK" button does not fire any 'createAnnotation' event. Nothing shows up in the console window as well. 

However, if I manually type a string in the widget, then I am able to create the annotation. And this time clicking on "OK" button fires the 'createAnnotation' event. Let me know if you need any further information.

**Comment by rsimon** [comment] 2020-09-24 12:56
Ouch - indeed, a regression error that sneaked in with a recent update. Thanks for reporting! Already found the offending piece of code and fixed it. Will go live with the next release (which will happen within the next week).

**Comment by neocheema** [comment] 2020-09-24 13:00
Superb, you guys are really active. I will wait. Cheers.

**Comment by neocheema** [comment] 2020-09-24 13:04
May I add a small feature request, while you are at it? 

Can the users "see" the predefined tags after selecting the area, inside the widget? Those could be selected via a mouse click. 

Currently, one has to press the "down" key, to open the dropdown list and then select the tag.

**Comment by rsimon** [comment] 2020-09-24 15:03
There's actually still discussion around that... the tag dropdown is meant to function as autocomplete. (I noticed now that this was also broken... will also be fixed in the next release.) Therefore, it shouldn't really open by default; also because people might use larger vocabularies.

When discussing the design with the initial customer, they wanted an "override" possibility nonetheless. Therefore the arrow-down option to show all tags. Frankly, the code for the dropdown widget is still a bit borked. There's probably going to be a rewrite for this at some point.

**Comment by neocheema** [comment] 2020-09-24 16:13
Understood. Waiting for your new release.

**Comment by rsimon** [comment] 2020-10-14 06:18
The tag widget autosuggest behavior is finally fixed (hopefully...) in all the latest releases: [Annotorious](https://github.com/recogito/annotorious/releases/tag/v2.1.3), [Annotorious OSD](https://github.com/recogito/annotorious/releases/tag/v2.1.3) and [RecogitoJS](https://github.com/recogito/recogito-js/releases/tag/v0.2.1). Cheers!

**Closed as completed by rsimon** 2020-10-14 06:18 UTC
