### ISSUE TITLE
The selectAnnotation stops firing after an exception is thrown

### ISSUE THREAD

**Issue by kennysong** [annotorious/annotorious#272] opened 2023-01-24 13:22 UTC
Hello! Sorry for filing several GitHub issues recently, our team is using this library a lot and has been bumping into edge cases. 

We've found that if the `selectAnnotation` event handler ever throws an exception, it breaks all future invocations of the event handler. This even persists after `anno.destroy()`!

Here's a minimal example to reproduce this bug: https://codepen.io/helloksong/pen/eYjMgvP

Steps to reproduce:
  1. Click on an annotation once, and the event handler fires
  2. Click on it again, and the event handler won't fire
  3. Run `anno.destroy()` and `initAnnotorious()` in the console
  4. Click on an annotation again, and the event handler won't fire

**Comment by rsimon** [comment] 2023-01-24 14:55
Hi,

hm - I'm not convinced that Annotorious should be responsible for isolating errors caused in the host application. Exceptions will generally break JS execution by design. If you know there's code that might raise an exception, then IMO the proper way is to handle it right there, inside the event handler. Otherwise, the app should crash rather than hide the error with a generic catch-call `catch`. So my personal take on this is: works as designed, TBH.

**Comment by kennysong** [comment] 2023-01-25 00:08
Thanks for the quick reply! 

Understood. It was surprising to us that an exception in an event handler seemed to break the internal state of Annotorious (unlike other libraries which can be more forgiving). This is something we can work around though, if exceptions are not allowed by design.

The additional surprising thing is that `anno.destroy()` doesn't fully reset/fix the state. We call `anno.destroy()` frequently to swap images+annotations in a single global `anno` instance. Is this okay or should we be resetting the object in a different way?

**Comment by rsimon** [comment] 2023-01-25 07:36
Ok, yes I can reproduce. I'll need to dig deeper to understand what's going on. Which means it will take a while until I actually find the time. As a workaround: best avoid exceptions for now ;-)

**Comment by kennysong** [comment] 2023-01-25 09:08
No problem, we will avoid exceptions in event handlers then. Thank you!

**Comment by rsimon** [comment] 2024-10-20 16:56
Closing as won't fix (in v2)

**Closed as completed by rsimon** 2024-10-20 16:56 UTC
Labels: bug, v2.x
