### ISSUE TITLE
Circle tool

### ISSUE THREAD

**Issue by ufuk23** [annotorious/annotorious#131] opened 2021-06-18 21:53 UTC
Have you got a plan to develop a circle tool? If so, when could we get this?

Best regards.

**Comment by rsimon** [comment] 2021-06-19 06:10
Hi @ufuk23,

interesting timing for this question :-) I __just now__ merged a pull request that adds a circle selection tool! If you build Annotorious yourself from source now, the circle tool is already there.

Until the next release, however, I'll refactor the project a bit. Annotorious will not get any additional selection tools. Instead there will be a new plugin (probably called `annotorious-selector-pack`). The circle tool will be the first tool to go into this new selector pack. I'll prepare all the docs when this gets released officially.

**Comment by ufuk23** [comment] 2021-06-19 09:12
> Hi @ufuk23,
> 
> interesting timing for this question :-) I **just now** merged a pull request that adds a circle selection tool! If you build Annotorious yourself from source now, the circle tool is already there.
> 
> Until the next release, however, I'll refactor the project a bit. Annotorious will not get any additional selection tools. Instead there will be a new plugin (probably called `annotorious-selector-pack`). The circle tool will be the first tool to go into this new selector pack. I'll prepare all the docs when this gets released officially.

**Comment by ufuk23** [comment] 2021-06-19 09:21
@rsimon, I made a circle tool for annotorious-openseadragon 2.1.4 version. now I get 2.4.1 version but I could not implement my circle tool with this version. The codes change rapidly and I could not change my circle tool. When I try to do that I get different runtime errors. I need a circle tool and I dont want to do it acoording to new versions.

Best regards.

**Comment by rsimon** [comment] 2021-06-19 09:40
If I had known about your tool, I could have sent your a warning that the tool API would change.

But as I said, a new circle tool is now part of the main branch, ready to use (if you build from source). With the next release, it will be available as official plugin for versions 2.4+.

**Comment by rsimon** [comment] 2021-06-19 10:45
Ah - another thing: the recent pull request that's now part of the main branch uses a non-standards-compliant format to store the circle shapes. I'll fix that before the official release. But just to let you know: circle annotations created with the current main branch will *not* be readable with the official release.

**Comment by ufuk23** [comment] 2021-06-19 14:11
I have just implemented the current main branch for the circle tool :) It looks great, at least it's better than mine, so please keep it in the main branch. The circle is so important and necessary tool I think there is no need to develop another tool. Now I am looking forward to get the new release. Take it easy!

**Comment by rsimon** [comment] 2021-06-19 16:14
Great, I'm already working on fixing the standards compliancy issue. Should be done soon!

**Comment by Hero-Solutions** [comment] 2021-06-19 16:15
Please be aware that there are still a few issues with the current implementation of the circle selection tool, so use this at your own risk until improvements have been made.

The main issue right now is that the circles are non-standard compliant. May not seem too important to you, but the implementation I had made (based on the work of @AlaEmrani) did not take into account the fact that CircleFragmentSelector is not a part of the W3C annotation model. As such, the CircleFragmentSelector will have to become an SvgSelector. Any stored circle fragments made with the current code will break once this change is released, 

There are also two visual bugs, although they are relatively minor compared to the one above:
- No visual mask has been implemented yet (dimming of the outer layer outside the circle when drawing or selected).
- When you drag a circle's handle all the way beyond the opposite handle, the handle disappears.

However, I currently won't be submitting any pull requests to fix these two bugs until the code has been refactored and I receive the go-ahead from @rsimon.

**Comment by rsimon** [comment] 2021-06-19 16:21
Hi @Hero-Solutions, the standards-compliance issue has a few implications on my own current code. (The SvgSelector implementation silently assumes that the SVG will always contain polygon. That clearly shouldn't be the case and needs fixing). But don't worry about it - I'm already working on it. I'll post an update to this thread as soon as I'm done.

**Comment by Hero-Solutions** [comment] 2021-06-19 16:25
I had tried to rework the SvgSelector code to make it work with both a circle and polygon, but it's proven too much of a challenge for me. I didn't know that you were already working on the compliancy yourself. I'll leave this one to you. Many thanks for following this up so quickly!

**Comment by rsimon** [comment] 2021-06-19 17:49
Done - the Circle tool now works with standards-compliant SvgSelectors :-) I'll refactor this into a plugin eventually, as I said. But meanwhile, do feel free to make changes and send PRs if there's anything you want to fix.

Many thanks again to everyone for making this happen, @Hero-Solutions and @AlaEmrani!

**Comment by Hero-Solutions** [comment] 2021-06-19 17:58
Awesome, thank you so much! I'll get to work with this right away to fix the two outstanding issues with the circle tool.

I would also like to include an ellipse and a free drawing and perhaps also a point selector. For now, I can simply develop these in my own fork without submitting them as pull requests, but I suppose others might have a use for these as well in the future.
To this end, is there anything that I should know before developing the extra selectors, so that merging them into this repository (or rather, the future plugin) won't require too many changes or adjustments?

**Comment by Hero-Solutions** [comment] 2021-06-19 21:20
Fixed the two outstanding issues with circle selection :) https://github.com/recogito/annotorious/pull/133

Hopefully the circle selection tool is fully implemented now. Please let me know if there still seem to be any issues or unintended behavior.

**Comment by rsimon** [comment] 2021-06-20 05:54
Thanks @Hero-Solutions,

For info: as planned, I moved the circle tool over to the new [Annotorious Selector Pack plugin project](https://github.com/recogito/annotorious-selector-pack). The plan is to make this plugin a collection of generally useful tools that people can optionally import into their projects.

**Comment by Hero-Solutions** [comment] 2021-06-20 09:46
Great! I do have a few questions regarding this new plugin:
- There is still a shape-related CSS rule present in the main repository (https://github.com/recogito/annotorious/blob/main/src/ImageAnnotator.scss#L28). Is there a way to generalize this, do we want to move these CSS rules into the plugin repository or do we have to alter this CSS rule in the main repo each time a new shape is added in the selector pack plugin?
- New CSS rules may have to be added (or existing rules altered) for new selectors, as was the case with the circle selector (faaba8f19cec8f3c00dab08e8cbc5109b352e163). How do we deal with this?
- Calculation of the area of a shape still happens in in the EmbeddedSVG selector in the main repository (https://github.com/recogito/annotorious/blob/main/src/selectors/EmbeddedSVG.js#L96). Do we leave this as-is (with the implication that each new shape in the plugin repository will also need their own method to calculate their area in the main repository) or are we going to look for a way to move these calculations into the selector pack plugin?
- The circle shape is still included in the main repository (https://github.com/recogito/annotorious/blob/main/src/tools/circle). Do we want to remove this now that the circle is contained in its own plugin repository?
- Are you planning to move the polygon into the shape repository? I'm guessing the answer would be no, even if it was just for backward compatibility (people wondering why their polygons suddenly don't work anymore after an update), but I figured I'd ask to make sure.

As far as I'm concerned, I don't really have a problem with shape-specific CSS rules and EmbeddedSVG code being in the main repository, but I want to be sure you're okay with these implications or if this needs to be worked out yet to make sure the selector pack plugin can operate entirely independent from the main repo.

**Comment by rsimon** [comment] 2021-06-20 10:00
Good points!

- I think the CSS rules should be moved over to the selector plugin. They are probably small, so can be embedded directly into the JS file. (No need to ship a separate CSS file with the selector pack I guess.)

- The area computations can remain in EmbeddedSVG I'd say. My thinking behind this is that these are concerns specific to all the SVG shape elements that exist - but not specific to the drawing tools. There could be drawing tools that work in totally different ways, but all produce polygons, for example. (In fact that's already the case: the TiltedBox plugin generates a polygon selector, just has different interaction.) Therefore I think it makes sense to keep these "SvgSelector-but-not-tool-specific" concerns with the core code.

**Comment by rsimon** [comment] 2021-06-20 10:04
- yes, the circle tool can be removed from the main code. Didn't delete it just yet, as long as the plugin isn't technically ready yet. But the whole circle folder will definitely be dropped before the next release.

- good question about the polygon drawing tool. I'm open to hearing opinions. But might be inclined to keep it, for backwards compatibility as you say.

**Comment by Hero-Solutions** [comment] 2021-06-20 10:05
Sounds good, thank you for the input! I can definitely agree with the shape-related area calculation being in EmbeddedSVG class, since different drawing tools don't necessarily produce different SVG shape elements.

I'd personally also keep the polygon drawing tool in the core code. Don't want to break other projects, unless there would be an automated way to prevent this from happening, which I wouldn't know about.

**Comment by Hero-Solutions** [comment] 2021-06-20 12:52
>     * I think the CSS rules should be moved over to the selector plugin. They are probably small, so can be embedded directly into the JS file. (No need to ship a separate CSS file with the selector pack I guess.)

Upon second thought, if you plan on keeping shape-specific area calculations in the core code, wouldn't it make sense to also keep shape-specific CSS rules inside the core code?

**Comment by rsimon** [comment] 2021-06-20 16:08
Good question... I don't have strong opinions about this. I assume different tools _might_ want to apply different styles (even for the same shape types), which would be an argument for keeping the styles in the tools. On the other hand, it probably makes sense to include sane base styles in the core distribution.

**Comment by ufuk23** [comment] 2021-06-21 09:55
@rsimon, thanks for your fast developments. We use the annotorious-openSeaDragon 2.4.1, how could I use the selector-pack with that? I tried the annotorious-selector-pack project alone but got some js errors. I think I must use these codes below with openSeadragon, right?

OpenSeadragon.Annotorious.SelectorPack(anno, {});
anno.setDrawingTool('circle');

**Comment by Hero-Solutions** [comment] 2021-06-21 11:20
@ufuk23 The following javascript code should do the trick:
```
Annotorious.SelectorPack(anno, {});
```

That's what worked for me, anyway (in Annotorious-OpenSeadragon).

And if you want to use the circle tool as default, you may also want to call ```anno.setDrawingTool('circle');```.

**Comment by ufuk23** [comment] 2021-06-21 11:42
![image](https://user-images.githubusercontent.com/8513827/122755917-5ce35480-d29e-11eb-845b-d3a438d115b8.png)

<script src="annotorious-selector-pack.min.js"></script>
Including the selector-pack.min.js and adding the code "Annotorious.SelectorPack(anno, {});" is not enough for me, because I get some js errors like above.

It works when I put the circle folder into the tools folder and add it ToolRegistery.js like the previous version v2.4.1

**Comment by rsimon** [comment] 2021-06-21 11:45
Hi @ufuk23, I haven't published an updated version of the OpenSeadragon plugin yet. That's probably why you're seeing the issue. I'll see if I can roll a new release this evening. 

Cheers,
R

**Comment by rsimon** [comment] 2021-06-22 19:25
Updated releases for Annotorious, AnnotoriousOSD and the Selector Pack are now on npm 🎉 Which means I think we can successfully close the issue. Thanks everyone!!

**Closed as completed by rsimon** 2021-06-22 19:25 UTC
